### ISSUE TITLE
Use C++11 compiler for continuous integration

### ISSUE THREAD

**Issue by bgrainger** [leutloff/diff-match-patch-cpp-stl#6]
It would be nice to use C++11 features in diff_match_patch. However, the Travis CI builds use older versions of gcc and clang that don't support C++11. Since C++11 support is generally widely available, could the Travis CI builds be updated to use newer compilers?

This would permit the use of:
* lambdas
* initializer lists
* `>>` for nested template arguments
* `unordered_map`
* and more

**Comment by leutloff** [comment]
Would the solution described in 
[C++11 Support with Travis-CI using g++](http://gearchicken.com/wordpress/?p=105)
be appropriate?

**Comment by leutloff** [comment]
IMHO, we can just switch to gcc-5. It is available from the same [PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise).

Updates to llvm are described at [http://llvm.org/apt/](http://llvm.org/apt/).

But, shouldn't this be addressed by the Travis CI people?

**Comment by leutloff** [comment]
Enabled C++11 in the build and using Trusty 14.04 as environment  237a824 and 7f95b37.
